# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jesc < Formula
  desc "DifA simple CLI tool to deeply unescape nested escaped JSON strings inside JSON objects."
  homepage "https://github.com/fardhanardhi/jesc"
  version "0.1.1"
  license "MIT License"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fardhanardhi/jesc/releases/download/v0.1.1/jesc_Darwin_x86_64.tar.gz"
      sha256 "4baea5da42ca0104c9240d7d09974ba4f709ab0bbca1b2a195a49df2d95c4554"

      def install
        bin.install "jesc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fardhanardhi/jesc/releases/download/v0.1.1/jesc_Darwin_arm64.tar.gz"
      sha256 "e39de3b97d38bcb06024f46bd3615af876e1175054166559895aec61111f065e"

      def install
        bin.install "jesc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/fardhanardhi/jesc/releases/download/v0.1.1/jesc_Linux_x86_64.tar.gz"
      sha256 "b89e40f07acde8e6b78f60643ee9cc3b43343d2b02f79cb39fe314b3149d88c6"
      def install
        bin.install "jesc"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/fardhanardhi/jesc/releases/download/v0.1.1/jesc_Linux_arm64.tar.gz"
      sha256 "54f46740f4fba5f79318832863cbe32f4f0b9b6e8a8630483d8cb9e5811c7dda"
      def install
        bin.install "jesc"
      end
    end
  end
end
